---
MainSourceFile:  '/home/intel/project/TransformerEnginev1.7-migration/3rdparty/cudnn-frontend/build/dpct_output/include/cudnn_frontend_EngineConfig.h'
Replacements:
  - FilePath:        '/home/intel/project/TransformerEnginev1.7-migration/3rdparty/cudnn-frontend/include/cudnn_frontend_EngineConfig.h'
    Offset:          1162
    Length:          0
    ReplacementText: "#define DPCT_PROFILING_ENABLED\n#include <sycl/sycl.hpp>\n#include <dpct/dpct.hpp>\n"
    ConstantFlag:    ''
    ConstantOffset:  0
    InitStr:         ''
    NewHostVarName:  ''
    BlockLevelFormatFlag: false
  - FilePath:        '/home/intel/project/TransformerEnginev1.7-migration/3rdparty/cudnn-frontend/include/cudnn_frontend_EngineConfig.h'
    Offset:          2307
    Length:          13
    ReplacementText: 'dpct::err1'
    ConstantFlag:    ''
    ConstantOffset:  0
    InitStr:         ''
    NewHostVarName:  ''
    BlockLevelFormatFlag: false
  - FilePath:        '/home/intel/project/TransformerEnginev1.7-migration/3rdparty/cudnn-frontend/include/cudnn_frontend_EngineConfig.h'
    Offset:          2384
    Length:          0
    ReplacementText: "            /*\n            DPCT1007:592: Migration of CUDNN_BACKEND_KNOB_CHOICE_DESCRIPTOR is not supported.\n            */\n"
    ConstantFlag:    ''
    ConstantOffset:  0
    InitStr:         ''
    NewHostVarName:  ''
    BlockLevelFormatFlag: false
  - FilePath:        '/home/intel/project/TransformerEnginev1.7-migration/3rdparty/cudnn-frontend/include/cudnn_frontend_EngineConfig.h'
    Offset:          3173
    Length:          0
    ReplacementText: "    /*\n    DPCT1007:593: Migration of CUDNN_KNOB_TYPE_COUNTS is not supported.\n    */\n"
    ConstantFlag:    ''
    ConstantOffset:  0
    InitStr:         ''
    NewHostVarName:  ''
    BlockLevelFormatFlag: false
  - FilePath:        '/home/intel/project/TransformerEnginev1.7-migration/3rdparty/cudnn-frontend/include/cudnn_frontend_EngineConfig.h'
    Offset:          4033
    Length:          13
    ReplacementText: 'dpct::err1'
    ConstantFlag:    ''
    ConstantOffset:  0
    InitStr:         ''
    NewHostVarName:  ''
    BlockLevelFormatFlag: false
  - FilePath:        '/home/intel/project/TransformerEnginev1.7-migration/3rdparty/cudnn-frontend/include/cudnn_frontend_EngineConfig.h'
    Offset:          4291
    Length:          0
    ReplacementText: "                                                   /*\n                                                   DPCT1007:594: Migration of CUDNN_ATTR_KNOB_CHOICE_KNOB_TYPE is not supported.\n                                                   */\n"
    ConstantFlag:    ''
    ConstantOffset:  0
    InitStr:         ''
    NewHostVarName:  ''
    BlockLevelFormatFlag: false
  - FilePath:        '/home/intel/project/TransformerEnginev1.7-migration/3rdparty/cudnn-frontend/include/cudnn_frontend_EngineConfig.h'
    Offset:          4376
    Length:          0
    ReplacementText: "                                                   /*\n                                                   DPCT1007:595: Migration of CUDNN_TYPE_KNOB_TYPE is not supported.\n                                                   */\n"
    ConstantFlag:    ''
    ConstantOffset:  0
    InitStr:         ''
    NewHostVarName:  ''
    BlockLevelFormatFlag: false
  - FilePath:        '/home/intel/project/TransformerEnginev1.7-migration/3rdparty/cudnn-frontend/include/cudnn_frontend_EngineConfig.h'
    Offset:          4588
    Length:          20
    ReplacementText: '0'
    ConstantFlag:    ''
    ConstantOffset:  0
    InitStr:         ''
    NewHostVarName:  ''
    BlockLevelFormatFlag: false
  - FilePath:        '/home/intel/project/TransformerEnginev1.7-migration/3rdparty/cudnn-frontend/include/cudnn_frontend_EngineConfig.h'
    Offset:          5124
    Length:          0
    ReplacementText: "                                                   /*\n                                                   DPCT1007:596: Migration of CUDNN_ATTR_KNOB_CHOICE_KNOB_VALUE is not supported.\n                                                   */\n"
    ConstantFlag:    ''
    ConstantOffset:  0
    InitStr:         ''
    NewHostVarName:  ''
    BlockLevelFormatFlag: false
  - FilePath:        '/home/intel/project/TransformerEnginev1.7-migration/3rdparty/cudnn-frontend/include/cudnn_frontend_EngineConfig.h'
    Offset:          5210
    Length:          0
    ReplacementText: "                                                   /*\n                                                   DPCT1007:597: Migration of CUDNN_TYPE_INT64 is not supported.\n                                                   */\n"
    ConstantFlag:    ''
    ConstantOffset:  0
    InitStr:         ''
    NewHostVarName:  ''
    BlockLevelFormatFlag: false
  - FilePath:        '/home/intel/project/TransformerEnginev1.7-migration/3rdparty/cudnn-frontend/include/cudnn_frontend_EngineConfig.h'
    Offset:          5419
    Length:          20
    ReplacementText: '0'
    ConstantFlag:    ''
    ConstantOffset:  0
    InitStr:         ''
    NewHostVarName:  ''
    BlockLevelFormatFlag: false
  - FilePath:        '/home/intel/project/TransformerEnginev1.7-migration/3rdparty/cudnn-frontend/include/cudnn_frontend_EngineConfig.h'
    Offset:          5978
    Length:          20
    ReplacementText: '0'
    ConstantFlag:    ''
    ConstantOffset:  0
    InitStr:         ''
    NewHostVarName:  ''
    BlockLevelFormatFlag: false
  - FilePath:        '/home/intel/project/TransformerEnginev1.7-migration/3rdparty/cudnn-frontend/include/cudnn_frontend_EngineConfig.h'
    Offset:          6486
    Length:          20
    ReplacementText: '0'
    ConstantFlag:    ''
    ConstantOffset:  0
    InitStr:         ''
    NewHostVarName:  ''
    BlockLevelFormatFlag: false
  - FilePath:        '/home/intel/project/TransformerEnginev1.7-migration/3rdparty/cudnn-frontend/include/cudnn_frontend_EngineConfig.h'
    Offset:          6941
    Length:          22
    ReplacementText: '2000'
    ConstantFlag:    ''
    ConstantOffset:  0
    InitStr:         ''
    NewHostVarName:  ''
    BlockLevelFormatFlag: false
  - FilePath:        '/home/intel/project/TransformerEnginev1.7-migration/3rdparty/cudnn-frontend/include/cudnn_frontend_EngineConfig.h'
    Offset:          7189
    Length:          0
    ReplacementText: "        /*\n        DPCT1007:598: Migration of CUDNN_BACKEND_ENGINECFG_DESCRIPTOR is not supported.\n        */\n"
    ConstantFlag:    ''
    ConstantOffset:  0
    InitStr:         ''
    NewHostVarName:  ''
    BlockLevelFormatFlag: false
  - FilePath:        '/home/intel/project/TransformerEnginev1.7-migration/3rdparty/cudnn-frontend/include/cudnn_frontend_EngineConfig.h'
    Offset:          7321
    Length:          20
    ReplacementText: '0'
    ConstantFlag:    ''
    ConstantOffset:  0
    InitStr:         ''
    NewHostVarName:  ''
    BlockLevelFormatFlag: false
  - FilePath:        '/home/intel/project/TransformerEnginev1.7-migration/3rdparty/cudnn-frontend/include/cudnn_frontend_EngineConfig.h'
    Offset:          7645
    Length:          0
    ReplacementText: "                                               /*\n                                               DPCT1007:599: Migration of CUDNN_ATTR_ENGINECFG_ENGINE is not supported.\n                                               */\n"
    ConstantFlag:    ''
    ConstantOffset:  0
    InitStr:         ''
    NewHostVarName:  ''
    BlockLevelFormatFlag: false
  - FilePath:        '/home/intel/project/TransformerEnginev1.7-migration/3rdparty/cudnn-frontend/include/cudnn_frontend_EngineConfig.h'
    Offset:          7721
    Length:          0
    ReplacementText: "                                               /*\n                                               DPCT1007:600: Migration of CUDNN_TYPE_BACKEND_DESCRIPTOR is not supported.\n                                               */\n"
    ConstantFlag:    ''
    ConstantOffset:  0
    InitStr:         ''
    NewHostVarName:  ''
    BlockLevelFormatFlag: false
  - FilePath:        '/home/intel/project/TransformerEnginev1.7-migration/3rdparty/cudnn-frontend/include/cudnn_frontend_EngineConfig.h'
    Offset:          7972
    Length:          20
    ReplacementText: '0'
    ConstantFlag:    ''
    ConstantOffset:  0
    InitStr:         ''
    NewHostVarName:  ''
    BlockLevelFormatFlag: false
  - FilePath:        '/home/intel/project/TransformerEnginev1.7-migration/3rdparty/cudnn-frontend/include/cudnn_frontend_EngineConfig.h'
    Offset:          8337
    Length:          0
    ReplacementText: "            /*\n            DPCT1007:601: Migration of CUDNN_KNOB_TYPE_COUNTS is not supported.\n            */\n"
    ConstantFlag:    ''
    ConstantOffset:  0
    InitStr:         ''
    NewHostVarName:  ''
    BlockLevelFormatFlag: false
  - FilePath:        '/home/intel/project/TransformerEnginev1.7-migration/3rdparty/cudnn-frontend/include/cudnn_frontend_EngineConfig.h'
    Offset:          8689
    Length:          0
    ReplacementText: "                                                   /*\n                                                   DPCT1007:602: Migration of CUDNN_ATTR_ENGINECFG_KNOB_CHOICES is not supported.\n                                                   */\n"
    ConstantFlag:    ''
    ConstantOffset:  0
    InitStr:         ''
    NewHostVarName:  ''
    BlockLevelFormatFlag: false
  - FilePath:        '/home/intel/project/TransformerEnginev1.7-migration/3rdparty/cudnn-frontend/include/cudnn_frontend_EngineConfig.h'
    Offset:          8775
    Length:          0
    ReplacementText: "                                                   /*\n                                                   DPCT1007:603: Migration of CUDNN_TYPE_BACKEND_DESCRIPTOR is not supported.\n                                                   */\n"
    ConstantFlag:    ''
    ConstantOffset:  0
    InitStr:         ''
    NewHostVarName:  ''
    BlockLevelFormatFlag: false
  - FilePath:        '/home/intel/project/TransformerEnginev1.7-migration/3rdparty/cudnn-frontend/include/cudnn_frontend_EngineConfig.h'
    Offset:          9030
    Length:          20
    ReplacementText: '0'
    ConstantFlag:    ''
    ConstantOffset:  0
    InitStr:         ''
    NewHostVarName:  ''
    BlockLevelFormatFlag: false
  - FilePath:        '/home/intel/project/TransformerEnginev1.7-migration/3rdparty/cudnn-frontend/include/cudnn_frontend_EngineConfig.h'
    Offset:          9510
    Length:          20
    ReplacementText: '0'
    ConstantFlag:    ''
    ConstantOffset:  0
    InitStr:         ''
    NewHostVarName:  ''
    BlockLevelFormatFlag: false
MainSourceFilesDigest:
  - MainSourceFile:  '/home/intel/project/TransformerEnginev1.7-migration/3rdparty/cudnn-frontend/include/cudnn_frontend_EngineConfig.h'
    Digest:          04eb7f062272f9ad8af1edbb11047c2e
DpctVersion:     2024.2.0
MainHelperFileName: ''
USMLevel:        ''
FeatureMap:      {}
CompileTargets:  {}
OptionMap:
  AnalysisScopePath:
    Value:           '/home/intel/project/TransformerEnginev1.7-migration/3rdparty/cudnn-frontend'
    Specified:       false
  AsyncHandler:
    Value:           'false'
    Specified:       false
  BuildScript:
    Value:           '1'
    Specified:       true
  CodePinEnabled:
    Value:           'false'
    Specified:       false
  CommentsEnabled:
    Value:           'false'
    Specified:       false
  CompilationsDir:
    Value:           '/home/intel/project/TransformerEnginev1.7-migration/3rdparty/cudnn-frontend/build'
    Specified:       true
  CtadEnabled:
    Value:           'false'
    Specified:       false
  EnablepProfiling:
    Value:           'false'
    Specified:       false
  ExperimentalFlag:
    Value:           '0'
    Specified:       false
  ExplicitNamespace:
    Value:           '20'
    Specified:       false
  ExtensionDDFlag:
    Value:           '0'
    Specified:       false
  ExtensionDEFlag:
    Value:           '4294967295'
    Specified:       false
  HelperFuncPreferenceFlag:
    Value:           '0'
    Specified:       false
  NDRangeDim:
    Value:           '3'
    Specified:       false
  NoDRYPattern:
    Value:           'false'
    Specified:       false
  OptimizeMigration:
    Value:           'false'
    Specified:       false
  ProcessAll:
    Value:           'false'
    Specified:       false
  RuleFile:
    Value:           ''
    ValueVec:
      - '/opt/intel/oneapi/dpcpp-ct/2024.2/extensions/cmake_rules/cmake_script_migration_rule.yaml'
    Specified:       false
  SyclNamedLambda:
    Value:           'false'
    Specified:       false
  UsmLevel:
    Value:           '1'
    Specified:       false
...
